project:
  type: website
  output-dir: docs
  post-render:
    - "cp -rnv .well-known/. docs/.well-known/"

website:
  title: "Jeroen Van Goey"
  navbar:
    left:
      - href: index.qmd
        text: Home


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


