[project]
name = "biogeek-github-io"
version = "0.1.0"
description = "Personal website for Jeroen Van Goey"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.2",
    "pandas>=2.2.3",
]
